# Setup
title:               Thematic
tagline:             'A Jekyll theme'
description:         'Based on Lanyon, made by Forgenst'
url:                 https://blog.forgenst.com
baseurl:             '/minimal-madness'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ed Mason
  # Don't add protocol (i.e. http or https)
  url:               forgenst.com
  email:             ed@forgenst.com

# Gems
plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-sitemap

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
fontawesome: 01f55bc79f #fontawesome id here -> get one at https://fontawesome.com/start (Don't use mine!)
github:
  repo: https://github.com/forgenst/minimal-madness
