# Setup
title:               Thematic
tagline:             'A Jekyll theme'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer.'
url:                 https://thematic.forgenst.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ed Mason
  url:               https://forgenst.com
  email:             ed@forgenst.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
