# Setup
title:               Thematic
tagline:             'A Jekyll theme'
description:         ''
url:                 https://blog.forgenst.com
baseurl:             '/thematic'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ed Mason
  url:               https://forgenst.com
  email:             ed@forgenst.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
